// src/components/Commands.vue
<template>
  <div class="commands">
    <Skeletons active="activeSkeleton" />
    <Ranges />
    <!-- <Panner /> -->
    <Tapes />
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import Skeletons from './Skeletons.vue';
import Ranges from './Ranges.vue';
import Tapes from './Tapes.vue';

export default {
  name: 'Commands',
  components: {
    Skeletons,
    Ranges,
    Tapes,
  },
  computed: {
    ...mapGetters([
      'activeSkeleton',
    ]),
  },
};
</script>

// src/components/Commands.jsx
import React from 'react';
import { inject, observer } from 'mobx-react';
import Tapes from './Tapes';
import Skeletons from './Skeletons';

import '../css/commands';
import '../css/range';
import Ranges from './Ranges';
import CommandPad from './CommandPad';

const Commands = inject('recorderStore')(observer(({ recorderStore }) => {
  

  return (
    <div className="commands">
      <Skeletons active={recorderStore.activeSkeleton} />
      <Ranges />
      {/* <Panner /> */}
      <Tapes />
    </div>
  )
}));

export default Commands;
