// src/components/Notes.jsx
import React from 'react';
import { inject, observer } from 'mobx-react';
import NoteRow from './NoteRow'

const Notes = inject('recorderStore', 'notesStore')(observer(({ recorderStore, notesStore }) => {
  const playSound = () => (note) => recorderStore.playSound(note);

  return (
    <React.Fragment>
      <NoteRow activeNote={recorderStore.activeNote} notes={notesStore.notesRow1} onMouseDown={playSound()} />
      <br />
      <NoteRow activeNote={recorderStore.activeNote} notes={notesStore.notesRow2} onMouseDown={playSound()} />
      <br />
      <NoteRow activeNote={recorderStore.activeNote} notes={notesStore.notesRow3} onMouseDown={playSound()} />
    </React.Fragment>
  )
}));

export default Notes;

// src/components/Notes.vue
<template>
  <div>
    <NoteRow
      :active-note="activeNote"
      :notes="notesRow1"
      :on-mouse-down="playSound"
    />
    <br>
    <NoteRow
      :active-note="activeNote"
      :notes="notesRow2"
      :on-mouse-down="playSound"
    />
    <br>
    <NoteRow
      :active-note="activeNote"
      :notes="notesRow3"
      :on-mouse-down="playSound"
    />
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';
import NoteRow from './NoteRow.vue';

export default {
  name: 'Notes',
  components: {
    NoteRow,
  },
  computed: {
    ...mapGetters([
      'activeNote',
      'notesRow1',
      'notesRow2',
      'notesRow3',
    ]),
  },
  methods: {
    ...mapActions([
      'playSound',
    ]),
  },
};
</script>
