// src/components/Note.jsx
import React from 'react';

const Note = ({ note, shortcut, onMouseDown, activeNote }) => {
  const handleMouseDown = () => onMouseDown(note);
  return (
    <span className={`pad ${activeNote === note ? 'active' : ''}`} onMouseDown={handleMouseDown}>
    <span>{ note } <b>[{ shortcut }]</b></span>
  </span>
)
};

export default Note;

// src/components/Note.vue
<template>
  <span
    :class="classes"
    @mousedown="handleMouseDown"
  >
    <span>{{ note }} <b>[{{ shortcut }}]</b></span>
  </span>
</template>

<script>
export default {
  name: 'Note',
  props: {
    note: String,
    onMouseDown: Function,
    shortcut: String,
    activeNote: String,
  },
  computed: {
    classes() {
      return `pad ${this.activeNote === this.note ? 'active' : ''}`;
    },
  },
  methods: {
    handleMouseDown() {
      this.onMouseDown(this.note);
    },
  },
};
</script>
