// src/components/NoteRow.jsx
import React from 'react';
import Note from './Note';

const NoteRow = ({ notes, onMouseDown, activeNote }) => (
  <React.Fragment>
    {notes.map((note, idx) => 
      <Note activeNote={activeNote} note={note.note} shortcut={note.shortcut} onMouseDown={onMouseDown} key={idx + note} />
    )}
  </React.Fragment>
);

export default NoteRow;

// src/components/NoteRow.vue
<template>
  <div>
    <Note
      v-for="note in notes"
      active-note="activeNote"
      note="note.note"
      shortcut="note.shortcut"
      on-mouse-down="onMouseDown"
      :key="note.note"
    />
  </div>
</template>

<script>
export default {
  name: 'NoteRow',
  props: {
    activeNote: String,
    notes: Array,
    onMouseDown: Function,
  },
};
</script>
