// src/components/Panner.vue
<template>
  <div :class="classes" @click="togglePanner()" @mousemove="setPanner(event)">
    Panner
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';

export default {
  name: 'Panner',
  computed: {
    ...mapGetters([
      'activatePanner',
    ]),
    classes() {
      return `panner ${this.activatePanner ? 'active' : ''}`;
    },
  },
  methods: {
    ...mapActions([
      'togglePanner',
      'setPanner',
    ]),
  },
};
</script>

// src/components/Panner.jsx
import React from 'react';
import { inject, observer } from 'mobx-react';

const Panner = inject('recorderStore')(observer(({ recorderStore }) => {
  const togglePanner = () => recorderStore.togglePanner();
  const setPanner = (event) => recorderStore.setPanner(event);

  return (
    <div className={`panner ${recorderStore.activatePanner ? 'active' : ''}`} onClick={togglePanner} onMouseMove={setPanner}>
      Panner
    </div>
  )
}));

export default Panner;
