// src/components/Ranges.jsx
import React from 'react';
import { inject, observer } from 'mobx-react';

const Ranges = inject('recorderStore')(observer(({ recorderStore }) => {
  const setVolume = (event) => recorderStore.setVolume(event.target.value);
  const setNoteLength = (event) => recorderStore.setNoteLength(event.target.value);
  const setOctave = (event) => recorderStore.setOctave(event.target.value);

  return (
    <div className="ranges">
      <input type="range" min="0.1" max="1" value={recorderStore.volume} step="0.01" onChange={setVolume} />
      <input type="range" min="0.1" max="10" value={recorderStore.noteLength} step="0.01" onChange={setNoteLength} />
      <input type="range" min="0" max="7" value={recorderStore.octave} onChange={setOctave} />
      <div>
        <div className="command-label">
          Volume
          </div>
        <div className="command-label">
          Length
          </div>
        <div className="command-label">
          Octave
          </div>
      </div>
    </div>
  )
}));

export default Ranges;

// src/components/Ranges.vue
<template>
  <div class="ranges">
    <input
      type="range"
      min="0.1"
      max="1"
      value="volume"
      step="0.01"
      @change="setVolume(event.target.value)" />
    <input
      type="range"
      min="0.1"
      max="10"
      value="noteLength"
      step="0.01"
      @change="setNoteLength(event.target.value)" />
    <input
      type="range"
      min="0"
      max="7"
      value="octave"
      @change="setOctave(event.target.value)" />
    <div>
      <div class="command-label">
        Volume
        </div>
      <div class="command-label">
        Length
        </div>
      <div class="command-label">
        Octave
        </div>
    </div>
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';

export default {
  name: 'Ranges',
  computed: {
    ...mapGetters([
      'volume',
      'noteLength',
      'octave',
    ]),
  },
  methods: {
    ...mapActions([
      'setVolume',
      'setNoteLength',
      'setOctave',
    ]),
  },
};
</script>
