// src/components/Skeletons.jsx
import React from 'react';
import Skeleton from './Skeleton';

const skeletonsAmount = [0,1,2,3,4];

const Skeletons = ({ active }) => (
  <div className="skeletons-container">
    {skeletonsAmount.map((_, idx) => 
      <Skeleton active={active} order={idx + 1} key={idx + 1} />
    )}
  </div>
);

export default Skeletons;

// src/components/Skeletons.vue
<template>
  <div class="skeletons-container">
    <Skeleton v-for="n in 5" :active="active" :order="n" :key="n" />
  </div>
</template>

<script>
import Skeleton from './Skeleton.vue';

export default {
  name: 'Skeletons',
  components: {
    Skeleton,
  },
  props: {
    active: Number,
  },
};
</script>
