// src/components/Tapes.jsx
import React from 'react';
import TrackButton from './TrackButton';
import { inject, observer } from 'mobx-react';

const tapesAmount = [0,1,2,3];

const Tapes = inject('recorderStore')(observer(({ active, recorderStore }) => {
  const setTrack = () => (trackNumber) => () => recorderStore.setTrack(trackNumber);

  return (
    <div className="tapes-container">
      <div>
        {tapesAmount.map((_, idx) =>
          <TrackButton
            active={recorderStore.tape[idx].active}
            current={recorderStore.tape[idx].current}
            track={idx}
            key={idx}
            onClick={setTrack(idx)} />
        )}
      </div>
    </div>
  )
}));

export default Tapes;

// src/components/Tapes.vue
<template>
  <div class="tapes-container">
      <TrackButton
        v-for="n in 4"
        active="recorderStore.tape[n - 1].active"
        current="recorderStore.tape[n - 1].current"
        track="n"
        :key="n"
        on-click="setTrack" />
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';
import TrackButton from './TrackButton.vue';

export default {
  name: 'Tapes',
  components: {
    TrackButton,
  },
  computed: {
    ...mapGetters([
      'tape',
    ]),
  },
  methods: {
    ...mapActions([
      'setTrack',
    ]),
  },
};
</script>
